### ISSUE TITLE
deploy directus on Kubernetes

### ISSUE THREAD

**Issue by dfuriet** [directus-labs/helm-chart#30]
Hi,

I want to deploy directus helm chart but I have CrashLoopBackOff of directus container

with kubectl get logs directus-release-xxxxx errors is below. Is directus dont read directus-secret created in value.yml ?

Thank you to help me

Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: YES)
    at Handshake.Sequence._packetToError (C:\xampp\htdocs\directus\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Handshake.ErrorPacket (C:\xampp\htdocs\directus\node_modules\mysql\lib\protocol\sequences\Handshake.js:123:18)
    at Protocol._parsePacket (C:\xampp\htdocs\directus\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\xampp\htdocs\directus\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\xampp\htdocs\directus\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\xampp\htdocs\directus\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\xampp\htdocs\directus\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\xampp\htdocs\directus\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Protocol._enqueue (C:\xampp\htdocs\directus\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (C:\xampp\htdocs\directus\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at Connection.connect (C:\xampp\htdocs\directus\node_modules\mysql\lib\Connection.js:116:18)
    at C:\xampp\htdocs\directus\node_modules\knex\lib\dialects\mysql\index.js:66:18
    at new Promise (<anonymous>)
    at Client_MySQL.acquireRawConnection (C:\xampp\htdocs\directus\node_modules\knex\lib\dialects\mysql\index.js:61:12)
    at create (C:\xampp\htdocs\directus\node_modules\knex\lib\client.js:247:39)

**Comment by mikesindieiev** [comment]
Hello! Could you share your` values.yaml`?

**Comment by eli-tbd** [comment]
same issue, moving to use rds on aws. not locally on k8s

**Comment by mikesindieiev** [comment]
Hello @eli-tbd. Which chart version do you use? And could you share your values.yaml. I assume the issue is in resources left after chart reinstall

**Comment by eli-tbd** [comment]
right need to manually delete secrets but anyways i used DB_CONNECTION_STRING instead of the chart postgres

**Comment by mikesindieiev** [comment]
Could you share your values.yaml and which chart version do you use? 

I am not sure that we have DB_CONNECTION_STRING somewhere in the values
